const tools=[
{id:'scanner',name:'Document Scanner',icon:'▣',desc:'Scan paper documents from your camera.',tags:'scanner scan document camera'},
{id:'ocr',name:'Image → Text',icon:'T',desc:'Extract editable text from an image.',tags:'ocr image text extract'},
{id:'image-pdf',name:'Image → PDF',icon:'▤',desc:'Turn one or many images into a clean PDF.',tags:'image pdf jpg png convert'},
{id:'pdf-image',name:'PDF → JPG / PNG',icon:'▥',desc:'Convert PDF pages into images.',tags:'pdf jpg png convert'},
{id:'merge',name:'Merge PDF',icon:'⊞',desc:'Combine multiple PDFs into one file.',tags:'pdf merge combine'},
{id:'split',name:'Split PDF',icon:'÷',desc:'Split a PDF into selected pages.',tags:'pdf split separate'},
{id:'compress-image',name:'Compress Image',icon:'◌',desc:'Reduce image size for faster sharing.',tags:'image compress resize'},
{id:'jpg-png',name:'JPG ↔ PNG',icon:'↔',desc:'Convert images between JPG and PNG.',tags:'jpg png image convert'},
{id:'share',name:'Share & Send',icon:'↗',desc:'Send a file using a temporary sharing flow.',tags:'share send file'},
{id:'temporary',name:'Temporary Link',icon:'⌁',desc:'Create a short-lived file link when supported.',tags:'temporary link share'}
];
const grid=document.getElementById('toolGrid'),empty=document.getElementById('emptyState'),search=document.getElementById('toolSearch');
function render(q=''){
 const x=q.trim().toLowerCase();const list=x?tools.filter(t=>(t.name+' '+t.desc+' '+t.tags).toLowerCase().includes(x)):tools;
 grid.innerHTML=list.map(t=>`<button class="tool-card" data-tool-id="${t.id}"><span class="tool-icon">${t.icon}</span><h3>${t.name}</h3><p>${t.desc}</p><span class="use">Use tool →</span></button>`).join('');
 empty.hidden=!!list.length;grid.querySelectorAll('[data-tool-id]').forEach(b=>b.addEventListener('click',()=>openTool(b.dataset.toolId)));
}
const modal=document.getElementById('toolModal'),modalTitle=document.getElementById('modalTitle'),modalText=document.getElementById('modalText'),modalKicker=document.getElementById('modalKicker'),modalBody=document.getElementById('modalBody');
function openTool(id){const t=tools.find(x=>x.id===id);if(!t)return;modalTitle.textContent=t.name;modalKicker.textContent='KWIKTOOLFORALL · '+t.name.toUpperCase();modalText.textContent=t.desc;
 if(id==='image-pdf') buildImagePdf(); else modalBody.innerHTML=`<div style="padding:16px;border:1px dashed var(--line);border-radius:14px;background:rgba(91,124,255,.03)"><strong>Workspace coming next.</strong><p style="color:var(--muted);font-size:12px;margin-bottom:0">The tool entry is ready. Its processing workspace will be connected in the next build.</p></div>`;
 modal.classList.add('open');modal.setAttribute('aria-hidden','false');}
function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');}
document.getElementById('modalClose').addEventListener('click',closeModal);modal.addEventListener('click',e=>{if(e.target.dataset.close)closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});

/* Local browser PDF engine: images are rendered onto white PDF pages. */
function kwikAscii(s){return new TextEncoder().encode(s)}
function kwikDataUrlToBytes(data){const b64=data.split(',')[1];const bin=atob(b64);const out=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)out[i]=bin.charCodeAt(i);return out}
function kwikPdfEsc(s){return String(s).replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)')}
function kwikConcat(parts){let n=0;for(const p of parts)n+=p.length;const out=new Uint8Array(n);let o=0;for(const p of parts){out.set(p,o);o+=p.length}return out}
function kwikMakePdf(pages){
 const objects=[];const add=s=>{const bytes=typeof s==='string'?kwikAscii(s):s;objects.push(bytes);return objects.length};
 const catalog=add('');const pagesObj=add('');const pageRefs=[];const contentRefs=[];const imageRefs=[];
 for(const p of pages){
  const imgHeader=kwikAscii(`<< /Type /XObject /Subtype /Image /Width ${p.imgWidth} /Height ${p.imgHeight} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${p.jpeg.length} >>\nstream\n`);
  const img=kwikConcat([imgHeader,p.jpeg,kwikAscii('\nendstream')]);imageRefs.push(add(img));
  const content=kwikAscii(`q\n${p.width.toFixed(3)} 0 0 ${p.height.toFixed(3)} 0 0 cm\n/Im${imageRefs.length} Do\nQ\n`);
  const contentObj=kwikConcat([kwikAscii(`<< /Length ${content.length} >>\nstream\n`),content,kwikAscii('endstream')]);contentRefs.push(add(contentObj));
  pageRefs.push(add(''));
 }
 const font=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');
 objects[catalog-1]=kwikAscii(`<< /Type /Catalog /Pages ${pagesObj} 0 R >>`);
 objects[pagesObj-1]=kwikAscii(`<< /Type /Pages /Kids [${pageRefs.map(x=>x+' 0 R').join(' ')}] /Count ${pageRefs.length} >>`);
 for(let i=0;i<pages.length;i++) objects[pageRefs[i]-1]=kwikAscii(`<< /Type /Page /Parent ${pagesObj} 0 R /MediaBox [0 0 ${pages[i].width.toFixed(3)} ${pages[i].height.toFixed(3)}] /Resources << /XObject << /Im${i+1} ${imageRefs[i]} 0 R >> /Font << /F1 ${font} 0 R >> >> /Contents ${contentRefs[i]} 0 R >>`);
 let out=[kwikAscii('%PDF-1.4\n%\xFF\xFF\xFF\xFF\n')];const offsets=[0];let pos=out[0].length;
 for(let i=0;i<objects.length;i++){const head=kwikAscii(`${i+1} 0 obj\n`),tail=kwikAscii('\nendobj\n');offsets[i+1]=pos;out.push(head,objects[i],tail);pos+=head.length+objects[i].length+tail.length}
 const xrefPos=pos;let xref=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n`;for(let i=1;i<offsets.length;i++)xref+=String(offsets[i]).padStart(10,'0')+' 00000 n \n';xref+=`trailer\n<< /Size ${objects.length+1} /Root ${catalog} 0 R >>\nstartxref\n${xrefPos}\n%%EOF`;
 out.push(kwikAscii(xref));return new Blob(out,{type:'application/pdf'});
}

let pdfImages=[];let selectedPdfPage=0;let selectedPages=new Set();let previewIndex=0;
function buildImagePdf(){modalBody.innerHTML=`<div class="pdf-workspace">
 <div class="pdf-toolbar"><div class="dropzone" id="pdfDrop"><strong>Add JPG or PNG images</strong><span>Drag & drop multiple images here, or choose from your device.</span><label class="pick-btn" for="pdfFiles">Choose images</label><input id="pdfFiles" type="file" accept="image/jpeg,image/png" multiple hidden></div><button class="danger-btn" id="clearPdf">Clear All</button></div>
 <div class="pdf-settings"><div class="setting"><label>Bulk size</label><select id="pageSize"><option value="A4">A4</option><option value="Letter">Letter</option><option value="image">Image size</option></select></div><div class="setting"><label>Bulk orientation</label><select id="orientation"><option value="auto">Auto</option><option value="portrait">Portrait</option><option value="landscape">Landscape</option></select></div><div class="setting"><label>Bulk margin</label><select id="margin"><option value="10">10 mm</option><option value="5">5 mm</option><option value="0">0 mm</option></select></div></div>
 <div class="bulk-bar" id="bulkBar"><div class="setting"><label>Selected size</label><select id="bulkSize"><option value="A4">A4</option><option value="Letter">Letter</option><option value="image">Image size</option></select></div><div class="setting"><label>Selected orientation</label><select id="bulkOrientation"><option value="auto">Auto</option><option value="portrait">Portrait</option><option value="landscape">Landscape</option></select></div><div class="setting"><label>Selected margin</label><select id="bulkMargin"><option value="10">10 mm</option><option value="5">5 mm</option><option value="0">0 mm</option></select></div><button class="primary-btn apply" id="applySelected">Apply to selected</button></div>
 <div class="pages-head"><strong>DOCUMENT PAGES</strong><span id="pageCount">0 pages</span></div><div class="image-list" id="imageList"></div><div class="pdf-footer-actions"><button class="select-all-btn" id="selectAllPages">Select all</button><button class="primary-btn" id="createPdf">Create PDF</button></div><div class="pdf-status" id="pdfStatus">Add images to get started.</div>
 <div class="success-panel" id="pdfSuccess"><h3>Thank you for using KwikToolForAll.</h3><p>Your file is now downloaded.<br>Please check your Downloads folder.</p><div class="privacy-confirm"><strong>✓ Your privacy is protected</strong><br>Your images were processed locally in your browser and were not uploaded to our servers. Temporary workspace data has been cleared.</div><button class="reuse-btn" id="reusePdf">↻ Re-use the tool</button></div>
 </div>
 <div class="pdf-preview-modal" id="pdfPreviewModal"><div class="pdf-preview-backdrop" data-preview-close="1"></div><div class="pdf-preview-dialog"><div class="pdf-preview-top"><strong id="previewTitle">Page preview</strong><button class="preview-close" id="previewClose">×</button></div><div class="pdf-preview-stage" id="pdfPreviewStage"></div><div class="pdf-preview-controls"><div class="setting"><label>Size</label><select id="previewSize"><option value="A4">A4</option><option value="Letter">Letter</option><option value="image">Image size</option></select></div><div class="setting"><label>Orientation</label><select id="previewOrientation"><option value="auto">Auto</option><option value="portrait">Portrait</option><option value="landscape">Landscape</option></select></div><div class="setting"><label>Margin</label><select id="previewMargin"><option value="10">10 mm</option><option value="5">5 mm</option><option value="0">0 mm</option></select></div><button class="rotate-preview" id="previewRotate">↻ Rotate image</button></div></div></div>`;
 pdfImages=[];selectedPages.clear();selectedPdfPage=0;previewIndex=0;wirePdfTool();renderPdfImages();
}
function wirePdfTool(){
 const fileInput=document.getElementById('pdfFiles'),drop=document.getElementById('pdfDrop'),list=document.getElementById('imageList');
 fileInput.addEventListener('change',()=>addPdfFiles([...fileInput.files]));['dragenter','dragover'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.add('dragover')}));['dragleave','drop'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.remove('dragover')}));drop.addEventListener('drop',e=>addPdfFiles([...e.dataTransfer.files]));
 document.getElementById('clearPdf').addEventListener('click',clearPdfWorkspace);document.getElementById('selectAllPages').addEventListener('click',()=>{if(selectedPages.size===pdfImages.length)selectedPages.clear();else pdfImages.forEach((_,i)=>selectedPages.add(i));renderPdfImages()});document.getElementById('applySelected').addEventListener('click',applySelectedSettings);document.getElementById('createPdf').addEventListener('click',createImagePdf);document.getElementById('reusePdf').addEventListener('click',()=>{document.getElementById('pdfSuccess').classList.remove('show');renderPdfImages();});
 list.addEventListener('click',e=>{const row=e.target.closest('.image-row');if(!row)return;const i=Number(row.dataset.index);const action=e.target.closest('[data-action]')?.dataset.action;if(!action){openPdfPreview(i);return}if(action==='up'&&i>0){[pdfImages[i-1],pdfImages[i]]=[pdfImages[i],pdfImages[i-1]];selectedPdfPage=i-1}if(action==='down'&&i<pdfImages.length-1){[pdfImages[i+1],pdfImages[i]]=[pdfImages[i],pdfImages[i+1]];selectedPdfPage=i+1}if(action==='rotate'){pdfImages[i].rotation=(pdfImages[i].rotation+90)%360;selectedPdfPage=i}if(action==='remove'){URL.revokeObjectURL(pdfImages[i].url);pdfImages.splice(i,1);selectedPages=new Set([...selectedPages].filter(x=>x!==i).map(x=>x>i?x-1:x));if(selectedPdfPage>=pdfImages.length)selectedPdfPage=Math.max(0,pdfImages.length-1)}renderPdfImages()});
 list.addEventListener('change',e=>{const check=e.target.closest('.page-check');if(check){const i=Number(check.dataset.index);check.checked?selectedPages.add(i):selectedPages.delete(i);renderPdfImages();return}const s=e.target.closest('select[data-setting]');if(!s)return;const i=Number(s.closest('.image-row').dataset.index);pdfImages[i][s.dataset.setting]=s.dataset.setting==='margin'?Number(s.value):s.value;selectedPdfPage=i});
 document.getElementById('previewClose').addEventListener('click',closePdfPreview);document.getElementById('pdfPreviewModal').addEventListener('click',e=>{if(e.target.dataset.previewClose)closePdfPreview()});
 ['previewSize','previewOrientation','previewMargin'].forEach(id=>document.getElementById(id).addEventListener('change',updatePdfPreview));document.getElementById('previewRotate').addEventListener('click',()=>{pdfImages[previewIndex].rotation=(pdfImages[previewIndex].rotation+90)%360;renderPdfImages();updatePdfPreview()});
}
function addPdfFiles(files){files.filter(f=>/^image\/(jpeg|png)$/.test(f.type)).forEach(file=>{const url=URL.createObjectURL(file);pdfImages.push({url,name:file.name,width:0,height:0,rotation:0,pageSize:'A4',orientation:'auto',margin:10});const img=new Image();img.onload=()=>{pdfImages[pdfImages.length-1].width=img.naturalWidth;pdfImages[pdfImages.length-1].height=img.naturalHeight;renderPdfImages()};img.src=url});renderPdfImages();}
function clearPdfWorkspace(){pdfImages.forEach(x=>{try{URL.revokeObjectURL(x.url)}catch(e){}});pdfImages=[];selectedPages.clear();selectedPdfPage=0;previewIndex=0;const fi=document.getElementById('pdfFiles');if(fi)fi.value='';closePdfPreview();renderPdfImages()}
function renderPdfImages(){const list=document.getElementById('imageList');if(!list)return;document.getElementById('pageCount').textContent=`${pdfImages.length} page${pdfImages.length===1?'':'s'}`;document.getElementById('bulkBar').classList.toggle('show',selectedPages.size>0);document.getElementById('selectAllPages').textContent=pdfImages.length&&selectedPages.size===pdfImages.length?'Clear selection':'Select all';list.innerHTML=pdfImages.map((x,i)=>`<div class="image-row" data-index="${i}"><input class="page-check" data-index="${i}" type="checkbox" ${selectedPages.has(i)?'checked':''} aria-label="Select page ${i+1}"><button class="thumb-btn" title="Open large live preview"><img src="${x.url}" alt="${x.name}"></button><div class="page-meta"><strong>Page ${i+1}</strong><small>${x.name}</small></div><div class="row-actions"><button data-action="up" title="Move up">↑</button><button data-action="down" title="Move down">↓</button><button data-action="rotate" title="Rotate">↻</button><button data-action="remove" title="Remove">×</button></div><div class="row-settings"><select data-setting="pageSize" aria-label="Page ${i+1} size"><option value="A4" ${x.pageSize==='A4'?'selected':''}>A4</option><option value="Letter" ${x.pageSize==='Letter'?'selected':''}>Letter</option><option value="image" ${x.pageSize==='image'?'selected':''}>Image size</option></select><select data-setting="orientation" aria-label="Page ${i+1} orientation"><option value="auto" ${x.orientation==='auto'?'selected':''}>Auto</option><option value="portrait" ${x.orientation==='portrait'?'selected':''}>Portrait</option><option value="landscape" ${x.orientation==='landscape'?'selected':''}>Landscape</option></select><select data-setting="margin" aria-label="Page ${i+1} margin"><option value="10" ${x.margin===10?'selected':''}>10 mm</option><option value="5" ${x.margin===5?'selected':''}>5 mm</option><option value="0" ${x.margin===0?'selected':''}>0 mm</option></select></div></div>`).join('');document.getElementById('pdfStatus').textContent=pdfImages.length?'✓ Configure each page or select multiple pages for bulk changes.':'Add images to get started.'}
function applySelectedSettings(){const size=document.getElementById('bulkSize').value,orientation=document.getElementById('bulkOrientation').value,margin=Number(document.getElementById('bulkMargin').value);selectedPages.forEach(i=>{if(pdfImages[i]){pdfImages[i].pageSize=size;pdfImages[i].orientation=orientation;pdfImages[i].margin=margin}});renderPdfImages();document.getElementById('pdfStatus').textContent='✓ Settings applied to selected pages.'}
function getPageSize(item){let w=210,h=297;if(item.pageSize==='Letter'){w=215.9;h=279.4}if(item.pageSize==='image'){w=Math.max(10,item.width*25.4/96);h=Math.max(10,item.height*25.4/96)}if(item.orientation==='portrait'&&(w>h))[w,h]=[h,w];if(item.orientation==='landscape'&&(w<h))[w,h]=[h,w];if(item.orientation==='auto'){const imageLandscape=item.width>=item.height;if(imageLandscape&&(w<h))[w,h]=[h,w];if(!imageLandscape&&(w>h))[w,h]=[h,w]}return[w,h]}
function openPdfPreview(i){if(!pdfImages[i])return;previewIndex=i;const item=pdfImages[i];document.getElementById('pdfPreviewModal').classList.add('open');document.getElementById('previewTitle').textContent=`Page ${i+1} preview`;document.getElementById('previewSize').value=item.pageSize;document.getElementById('previewOrientation').value=item.orientation;document.getElementById('previewMargin').value=String(item.margin);updatePdfPreview()}
function closePdfPreview(){document.getElementById('pdfPreviewModal')?.classList.remove('open')}
function updatePdfPreview(){const stage=document.getElementById('pdfPreviewStage');if(!stage||!pdfImages[previewIndex])return;const item=pdfImages[previewIndex];item.pageSize=document.getElementById('previewSize').value;item.orientation=document.getElementById('previewOrientation').value;item.margin=Number(document.getElementById('previewMargin').value);const [w,h]=getPageSize(item);const maxW=Math.max(250,stage.clientWidth-50),maxH=Math.max(300,stage.clientHeight-50),scale=Math.min(maxW/w,maxH/h);const sheet=document.createElement('div');sheet.className='pdf-page-sheet';sheet.style.width=`${w*scale}px`;sheet.style.height=`${h*scale}px`;const img=document.createElement('img');img.src=item.url;img.style.width=`${Math.max(1,(w-item.margin*2)*scale)}px`;img.style.height=`${Math.max(1,(h-item.margin*2)*scale)}px`;img.style.left=`${item.margin*scale}px`;img.style.top=`${item.margin*scale}px`;img.style.transform=`rotate(${item.rotation}deg)`;img.style.transformOrigin='center center';sheet.appendChild(img);stage.innerHTML='';stage.appendChild(sheet)}
async function createImagePdf(){if(!pdfImages.length){document.getElementById('pdfStatus').textContent='Add at least one JPG or PNG image first.';return}const btn=document.getElementById('createPdf');btn.disabled=true;document.getElementById('pdfStatus').textContent='Creating PDF…';try{const pages=[];for(const item of pdfImages){const [pw,ph]=getPageSize(item);const marginMm=item.margin;const iw=Math.max(1,item.width*25.4/96),ih=Math.max(1,item.height*25.4/96);const maxW=Math.max(1,pw-marginMm*2),maxH=Math.max(1,ph-marginMm*2);const scale=Math.min(maxW/iw,maxH/ih);const w=iw*scale,h=ih*scale,x=(pw-w)/2,y=(ph-h)/2;const pxPerMm=96/25.4;const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(pw*pxPerMm));canvas.height=Math.max(1,Math.round(ph*pxPerMm));const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);const img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=()=>reject(new Error('Could not render image.'));img.src=item.url});ctx.save();ctx.translate((x+w/2)*pxPerMm,(y+h/2)*pxPerMm);ctx.rotate(item.rotation*Math.PI/180);ctx.drawImage(img,-(w*pxPerMm)/2,-(h*pxPerMm)/2,w*pxPerMm,h*pxPerMm);ctx.restore();pages.push({width:pw*72/25.4,height:ph*72/25.4,imgWidth:canvas.width,imgHeight:canvas.height,jpeg:kwikDataUrlToBytes(canvas.toDataURL('image/jpeg',.9))})}const blob=kwikMakePdf(pages);const href=URL.createObjectURL(blob);const a=document.createElement('a');a.href=href;a.download=`KwikToolForAll-images-${new Date().toISOString().slice(0,10)}.pdf`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(href),1000);clearPdfWorkspace();document.getElementById('pdfStatus').textContent='✓ PDF created and downloaded.';document.getElementById('pdfSuccess').classList.add('show')}catch(err){console.error(err);document.getElementById('pdfStatus').textContent='Could not create the PDF. Please try again with JPG or PNG images.'}finally{btn.disabled=false}}

function runSearch(q){search.value=q;render(q);document.getElementById('tools').scrollIntoView({behavior:'smooth',block:'start'})}document.getElementById('searchForm').addEventListener('submit',e=>{e.preventDefault();runSearch(search.value)});search.addEventListener('input',()=>render(search.value));document.querySelectorAll('[data-query]').forEach(b=>b.addEventListener('click',()=>runSearch(b.dataset.query)));document.querySelectorAll('[data-tool-id]').forEach(b=>b.addEventListener('click',()=>openTool(b.dataset.toolId)));document.getElementById('clearSearch').addEventListener('click',()=>{search.value='';render();document.getElementById('tools').scrollIntoView({behavior:'smooth'})});document.getElementById('resetSearch').addEventListener('click',()=>{search.value='';render()});document.getElementById('searchFocus').addEventListener('click',()=>{search.focus();document.querySelector('.hero').scrollIntoView({behavior:'smooth')});document.addEventListener('keydown',e=>{if(e.key==='/'&&document.activeElement!==search&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();search.focus()}});const themeBtn=document.getElementById('themeToggle'),saved=localStorage.getItem('kwikTheme');if(saved==='dark'){document.body.classList.add('dark');themeBtn.textContent='☀';themeBtn.setAttribute('aria-pressed','true')}themeBtn.addEventListener('click',()=>{const dark=document.body.classList.toggle('dark');themeBtn.textContent=dark?'☀':'☾';themeBtn.setAttribute('aria-pressed',String(dark));localStorage.setItem('kwikTheme',dark?'dark':'light')});const mobile=document.getElementById('mobileMenu'),nav=document.querySelector('.main-nav');mobile.addEventListener('click',()=>{const open=nav.classList.toggle('mobile-open');mobile.textContent=open?'×':'☰'});document.querySelectorAll('.nav-link').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('mobile-open');mobile.textContent='☰'}));const sections=[...document.querySelectorAll('main section[id]')],links=[...document.querySelectorAll('.nav-link')];const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+entry.target.id))}),{rootMargin:'-35% 0px -55% 0px',threshold:0});sections.forEach(s=>observer.observe(s));render();